package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import IPclLicenseServiceContract.CreateUserModel;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class CreateAdditionalUserModel implements KvmSerializable {
    
    public String adminUserGuid;
    public String lang;
    public String organizationGuid;
    public CreateUserModel user;
    
    public CreateAdditionalUserModel(){}
    
    public CreateAdditionalUserModel(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("AdminUserGuid"))
        {
            Object obj = soapObject.getProperty("AdminUserGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                adminUserGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                adminUserGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("Lang"))
        {
            Object obj = soapObject.getProperty("Lang");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lang = j.toString();
            }else if (obj!= null && obj instanceof String){
                lang = (String) obj;
            }
        }
        if (soapObject.hasProperty("OrganizationGuid"))
        {
            Object obj = soapObject.getProperty("OrganizationGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                organizationGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                organizationGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("User"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("User");
            user =  new CreateUserModel (j);
            
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 1:
                return adminUserGuid;
            case 2:
                return lang;
            case 3:
                return organizationGuid;
            case 4:
                return user;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 5;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "AdminUserGuid";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Lang";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "OrganizationGuid";
                break;
            case 4:
                info.type = CreateUserModel.class;
                info.name = "User";
                break;
        }
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
