package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import IPclLicenseServiceContract.UserDetailsModel;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class CreateUserModel implements KvmSerializable {
    
    public String email;
    public String password;
    public String returnUrlField;
    public String roleGuid;
    public UserDetailsModel userDetails;
    
    public CreateUserModel(){}
    
    public CreateUserModel(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Email"))
        {
            Object obj = soapObject.getProperty("Email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                email = j.toString();
            }else if (obj!= null && obj instanceof String){
                email = (String) obj;
            }
        }
        if (soapObject.hasProperty("Password"))
        {
            Object obj = soapObject.getProperty("Password");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                password = j.toString();
            }else if (obj!= null && obj instanceof String){
                password = (String) obj;
            }
        }
        if (soapObject.hasProperty("ReturnUrl"))
        {
            Object obj = soapObject.getProperty("ReturnUrl");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                returnUrlField = j.toString();
            }else if (obj!= null && obj instanceof String){
                returnUrlField = (String) obj;
            }
        }
        if (soapObject.hasProperty("RoleGuid"))
        {
            Object obj = soapObject.getProperty("RoleGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                roleGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                roleGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("UserDetails"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("UserDetails");
            userDetails =  new UserDetailsModel (j);
            
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 1:
                return email;
            case 2:
                return password;
            case 3:
                return returnUrlField;
            case 4:
                return roleGuid;
            case 5:
                return userDetails;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 6;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Email";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Password";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ReturnUrl";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "RoleGuid";
                break;
            case 5:
                info.type = UserDetailsModel.class;
                info.name = "UserDetails";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
