package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class DiscountModel implements KvmSerializable {
    

    public String activeFrom;
    public String disableAt;
    public double discountValue;
    public String guid;
    public String licensePlanGuid;
    public String productGuid;
    
    public DiscountModel(){}
    
    public DiscountModel(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ExtensionData"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ExtensionData");

            
        }
        if (soapObject.hasProperty("ActiveFrom"))
        {
            Object obj = soapObject.getProperty("ActiveFrom");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                activeFrom = j.toString();
            }else if (obj!= null && obj instanceof String){
                activeFrom = (String) obj;
            }
        }
        if (soapObject.hasProperty("DisableAt"))
        {
            Object obj = soapObject.getProperty("DisableAt");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                disableAt = j.toString();
            }else if (obj!= null && obj instanceof String){
                disableAt = (String) obj;
            }
        }
        if (soapObject.hasProperty("DiscountValue"))
        {
            Object obj = soapObject.getProperty("DiscountValue");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                discountValue = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                discountValue = (Double) obj;
            }
        }
        if (soapObject.hasProperty("Guid"))
        {
            Object obj = soapObject.getProperty("Guid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                guid = j.toString();
            }else if (obj!= null && obj instanceof String){
                guid = (String) obj;
            }
        }
        if (soapObject.hasProperty("LicensePlanGuid"))
        {
            Object obj = soapObject.getProperty("LicensePlanGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                licensePlanGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                licensePlanGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("ProductGuid"))
        {
            Object obj = soapObject.getProperty("ProductGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                productGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                productGuid = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return null;
            case 1:
                return activeFrom;
            case 2:
                return disableAt;
            case 3:
                return discountValue;
            case 4:
                return guid;
            case 5:
                return licensePlanGuid;
            case 6:
                return productGuid;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 7;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = null;
                info.name = "ExtensionData";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ActiveFrom";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DisableAt";
                break;
            case 3:
                info.type = Double.class;
                info.name = "DiscountValue";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Guid";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LicensePlanGuid";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ProductGuid";
                break;
        }
    }

    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
