package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import IPclLicenseServiceContract.WS_Enums.*;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class DiscountCodeVerificationModel implements KvmSerializable {
    

    public String discountCodeDefinitionGuid;
    public String discountCodeText;
    public String issuer;
    public String matchingLicensePlanGuid;
    public String productGuid;
    public DiscountCodeVerificationStatus status;
    public DiscountType type;
    public double value;
    
    public DiscountCodeVerificationModel(){}
    
    public DiscountCodeVerificationModel(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ExtensionData"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ExtensionData");

            
        }
        if (soapObject.hasProperty("DiscountCodeDefinitionGuid"))
        {
            Object obj = soapObject.getProperty("DiscountCodeDefinitionGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                discountCodeDefinitionGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                discountCodeDefinitionGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("DiscountCodeText"))
        {
            Object obj = soapObject.getProperty("DiscountCodeText");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                discountCodeText = j.toString();
            }else if (obj!= null && obj instanceof String){
                discountCodeText = (String) obj;
            }
        }
        if (soapObject.hasProperty("Issuer"))
        {
            Object obj = soapObject.getProperty("Issuer");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                issuer = j.toString();
            }else if (obj!= null && obj instanceof String){
                issuer = (String) obj;
            }
        }
        if (soapObject.hasProperty("MatchingLicensePlanGuid"))
        {
            Object obj = soapObject.getProperty("MatchingLicensePlanGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                matchingLicensePlanGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                matchingLicensePlanGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("ProductGuid"))
        {
            Object obj = soapObject.getProperty("ProductGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                productGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                productGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("Status"))
        {
            Object obj = soapObject.getProperty("Status");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive)obj;
                status = DiscountCodeVerificationStatus.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("Type"))
        {
            Object obj = soapObject.getProperty("Type");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive)obj;
                type = DiscountType.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("Value"))
        {
            Object obj = soapObject.getProperty("Value");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                value = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                value = (Double) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return null;
            case 1:
                return discountCodeDefinitionGuid;
            case 2:
                return discountCodeText;
            case 3:
                return issuer;
            case 4:
                return matchingLicensePlanGuid;
            case 5:
                return productGuid;
            case 6:
                return status.toString();
            case 7:
                return type.toString();
            case 8:
                return value;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 9;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = null;
                info.name = "ExtensionData";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DiscountCodeDefinitionGuid";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DiscountCodeText";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Issuer";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "MatchingLicensePlanGuid";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ProductGuid";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Status";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Type";
                break;
            case 8:
                info.type = Double.class;
                info.name = "Value";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
