package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class LicensePlanModel implements KvmSerializable {
    

    public String description;
    public double devicePricePerDayBrutto;
    public double devicePricePerDayBruttoEuro;
    public double devicePricePerDayNetto;
    public double devicePricePerDayNettoEuro;
    public double devicePricePerPeriodBrutto;
    public double devicePricePerPeriodBruttoEuro;
    public double devicePricePerPeriodNetto;
    public double devicePricePerPeriodNettoEuro;
    public boolean isFree;
    public String licensePlanGuid;
    public String name;
    public int periodDurationInDays;
    public Byte upgradeId;
    
    public LicensePlanModel(){}
    
    public LicensePlanModel(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ExtensionData"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ExtensionData");

            
        }
        if (soapObject.hasProperty("Description"))
        {
            Object obj = soapObject.getProperty("Description");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                description = j.toString();
            }else if (obj!= null && obj instanceof String){
                description = (String) obj;
            }
        }
        if (soapObject.hasProperty("DevicePricePerDayBrutto"))
        {
            Object obj = soapObject.getProperty("DevicePricePerDayBrutto");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                devicePricePerDayBrutto = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                devicePricePerDayBrutto = (Double) obj;
            }
        }
        if (soapObject.hasProperty("DevicePricePerDayBruttoEuro"))
        {
            Object obj = soapObject.getProperty("DevicePricePerDayBruttoEuro");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                devicePricePerDayBruttoEuro = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                devicePricePerDayBruttoEuro = (Double) obj;
            }
        }
        if (soapObject.hasProperty("DevicePricePerDayNetto"))
        {
            Object obj = soapObject.getProperty("DevicePricePerDayNetto");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                devicePricePerDayNetto = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                devicePricePerDayNetto = (Double) obj;
            }
        }
        if (soapObject.hasProperty("DevicePricePerDayNettoEuro"))
        {
            Object obj = soapObject.getProperty("DevicePricePerDayNettoEuro");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                devicePricePerDayNettoEuro = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                devicePricePerDayNettoEuro = (Double) obj;
            }
        }
        if (soapObject.hasProperty("DevicePricePerPeriodBrutto"))
        {
            Object obj = soapObject.getProperty("DevicePricePerPeriodBrutto");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                devicePricePerPeriodBrutto = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                devicePricePerPeriodBrutto = (Double) obj;
            }
        }
        if (soapObject.hasProperty("DevicePricePerPeriodBruttoEuro"))
        {
            Object obj = soapObject.getProperty("DevicePricePerPeriodBruttoEuro");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                devicePricePerPeriodBruttoEuro = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                devicePricePerPeriodBruttoEuro = (Double) obj;
            }
        }
        if (soapObject.hasProperty("DevicePricePerPeriodNetto"))
        {
            Object obj = soapObject.getProperty("DevicePricePerPeriodNetto");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                devicePricePerPeriodNetto = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                devicePricePerPeriodNetto = (Double) obj;
            }
        }
        if (soapObject.hasProperty("DevicePricePerPeriodNettoEuro"))
        {
            Object obj = soapObject.getProperty("DevicePricePerPeriodNettoEuro");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                devicePricePerPeriodNettoEuro = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                devicePricePerPeriodNettoEuro = (Double) obj;
            }
        }
        if (soapObject.hasProperty("IsFree"))
        {
            Object obj = soapObject.getProperty("IsFree");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                isFree = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                isFree = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("LicensePlanGuid"))
        {
            Object obj = soapObject.getProperty("LicensePlanGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                licensePlanGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                licensePlanGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("Name"))
        {
            Object obj = soapObject.getProperty("Name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                name = j.toString();
            }else if (obj!= null && obj instanceof String){
                name = (String) obj;
            }
        }
        if (soapObject.hasProperty("PeriodDurationInDays"))
        {
            Object obj = soapObject.getProperty("PeriodDurationInDays");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                periodDurationInDays = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                periodDurationInDays = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("UpgradeId"))
        {
            Object obj = soapObject.getProperty("UpgradeId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                upgradeId = Byte.parseByte(j.toString());
            }else if (obj!= null && obj instanceof Byte){
                upgradeId = (Byte) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return null;
            case 1:
                return description;
            case 2:
                return devicePricePerDayBrutto;
            case 3:
                return devicePricePerDayBruttoEuro;
            case 4:
                return devicePricePerDayNetto;
            case 5:
                return devicePricePerDayNettoEuro;
            case 6:
                return devicePricePerPeriodBrutto;
            case 7:
                return devicePricePerPeriodBruttoEuro;
            case 8:
                return devicePricePerPeriodNetto;
            case 9:
                return devicePricePerPeriodNettoEuro;
            case 10:
                return isFree;
            case 11:
                return licensePlanGuid;
            case 12:
                return name;
            case 13:
                return periodDurationInDays;
            case 14:
                return upgradeId.toString();
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 15;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = null;
                info.name = "ExtensionData";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Description";
                break;
            case 2:
                info.type = Double.class;
                info.name = "DevicePricePerDayBrutto";
                break;
            case 3:
                info.type = Double.class;
                info.name = "DevicePricePerDayBruttoEuro";
                break;
            case 4:
                info.type = Double.class;
                info.name = "DevicePricePerDayNetto";
                break;
            case 5:
                info.type = Double.class;
                info.name = "DevicePricePerDayNettoEuro";
                break;
            case 6:
                info.type = Double.class;
                info.name = "DevicePricePerPeriodBrutto";
                break;
            case 7:
                info.type = Double.class;
                info.name = "DevicePricePerPeriodBruttoEuro";
                break;
            case 8:
                info.type = Double.class;
                info.name = "DevicePricePerPeriodNetto";
                break;
            case 9:
                info.type = Double.class;
                info.name = "DevicePricePerPeriodNettoEuro";
                break;
            case 10:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "IsFree";
                break;
            case 11:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LicensePlanGuid";
                break;
            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Name";
                break;
            case 13:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "PeriodDurationInDays";
                break;
            case 14:
                info.type = Byte.class;
                info.name = "UpgradeId";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
