package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class ManagerData implements KvmSerializable {
    

    public String managerGuid;
    public String organizationGuid;
    
    public ManagerData(){}
    
    public ManagerData(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ExtensionData"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ExtensionData");

            
        }
        if (soapObject.hasProperty("ManagerGuid"))
        {
            Object obj = soapObject.getProperty("ManagerGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                managerGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                managerGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("OrganizationGuid"))
        {
            Object obj = soapObject.getProperty("OrganizationGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                organizationGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                organizationGuid = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return null;
            case 1:
                return managerGuid;
            case 2:
                return organizationGuid;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 3;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = null;
                info.name = "ExtensionData";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ManagerGuid";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "OrganizationGuid";
                break;
        }
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
