package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import IPclLicenseServiceContract.WS_Enums.*;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class NewDeviceLicenseResponse implements KvmSerializable {
    

    public int avaliableDevices;
    public CheckLicenseResultEnum licenseCheckResult;
    public String organizationGuid;
    public boolean success;
    
    public NewDeviceLicenseResponse(){}
    
    public NewDeviceLicenseResponse(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ExtensionData"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ExtensionData");

            
        }
        if (soapObject.hasProperty("AvaliableDevices"))
        {
            Object obj = soapObject.getProperty("AvaliableDevices");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                avaliableDevices = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                avaliableDevices = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("LicenseCheckResult"))
        {
            Object obj = soapObject.getProperty("LicenseCheckResult");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive)obj;
                licenseCheckResult = CheckLicenseResultEnum.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("OrganizationGuid"))
        {
            Object obj = soapObject.getProperty("OrganizationGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                organizationGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                organizationGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("Success"))
        {
            Object obj = soapObject.getProperty("Success");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                success = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                success = (Boolean) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return null;
            case 1:
                return avaliableDevices;
            case 2:
                return licenseCheckResult.toString();
            case 3:
                return organizationGuid;
            case 4:
                return success;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 5;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = null;
                info.name = "ExtensionData";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "AvaliableDevices";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LicenseCheckResult";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "OrganizationGuid";
                break;
            case 4:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "Success";
                break;
        }
    }
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
