package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import IPclLicenseServiceContract.WS_Enums.*;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class PurchaseLicenseResponseModel implements KvmSerializable {
    

    public DiscountCodeVerificationStatus discountCodeVerificationStatus;
    public String invoiceGuid;
    public boolean isSuccess;
    
    public PurchaseLicenseResponseModel(){}
    
    public PurchaseLicenseResponseModel(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ExtensionData"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ExtensionData");

            
        }
        if (soapObject.hasProperty("DiscountCodeVerificationStatus"))
        {
            Object obj = soapObject.getProperty("DiscountCodeVerificationStatus");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive)obj;
                discountCodeVerificationStatus = DiscountCodeVerificationStatus.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("InvoiceGuid"))
        {
            Object obj = soapObject.getProperty("InvoiceGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                invoiceGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                invoiceGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("IsSuccess"))
        {
            Object obj = soapObject.getProperty("IsSuccess");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                isSuccess = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                isSuccess = (Boolean) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return null;
            case 1:
                return discountCodeVerificationStatus.toString();
            case 2:
                return invoiceGuid;
            case 3:
                return isSuccess;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = null;
                info.name = "ExtensionData";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DiscountCodeVerificationStatus";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "InvoiceGuid";
                break;
            case 3:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "IsSuccess";
                break;
        }
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
