package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import IPclLicenseServiceContract.WS_Enums.*;

import IPclLicenseServiceContract.UserAccountModel;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class UpdateUserResultModel implements KvmSerializable {
    

    public boolean success;
    public UpdateUserStatus updateStatus;
    public UserAccountModel user;
    
    public UpdateUserResultModel(){}
    
    public UpdateUserResultModel(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ExtensionData"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ExtensionData");

            
        }
        if (soapObject.hasProperty("Success"))
        {
            Object obj = soapObject.getProperty("Success");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                success = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                success = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("UpdateStatus"))
        {
            Object obj = soapObject.getProperty("UpdateStatus");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive)obj;
                updateStatus = UpdateUserStatus.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("User"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("User");
            user =  new UserAccountModel (j);
            
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return null;
            case 1:
                return success;
            case 2:
                return updateStatus.toString();
            case 3:
                return user;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = null;
                info.name = "ExtensionData";
                break;
            case 1:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "Success";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "UpdateStatus";
                break;
            case 3:
                info.type = UserAccountModel.class;
                info.name = "User";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
