package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import IPclLicenseServiceContract.UserDetailsModel;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class UserAccountModel implements KvmSerializable {
    

    public String createdAt;
    public String email;
    public String guid;
    public boolean isActivated;
    public boolean isAdministrator;
    public boolean isDisabled;
    public String organizationGuid;
    public String organizationName;
    public String pin;
    public String roleGuid;
    public String roleName;
    public UserDetailsModel userDetails;
    
    public UserAccountModel(){}
    
    public UserAccountModel(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ExtensionData"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ExtensionData");

            
        }
        if (soapObject.hasProperty("CreatedAt"))
        {
            Object obj = soapObject.getProperty("CreatedAt");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                createdAt = j.toString();
            }else if (obj!= null && obj instanceof String){
                createdAt = (String) obj;
            }
        }
        if (soapObject.hasProperty("Email"))
        {
            Object obj = soapObject.getProperty("Email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                email = j.toString();
            }else if (obj!= null && obj instanceof String){
                email = (String) obj;
            }
        }
        if (soapObject.hasProperty("Guid"))
        {
            Object obj = soapObject.getProperty("Guid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                guid = j.toString();
            }else if (obj!= null && obj instanceof String){
                guid = (String) obj;
            }
        }
        if (soapObject.hasProperty("IsActivated"))
        {
            Object obj = soapObject.getProperty("IsActivated");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                isActivated = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                isActivated = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("IsAdministrator"))
        {
            Object obj = soapObject.getProperty("IsAdministrator");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                isAdministrator = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                isAdministrator = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("IsDisabled"))
        {
            Object obj = soapObject.getProperty("IsDisabled");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                isDisabled = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                isDisabled = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("OrganizationGuid"))
        {
            Object obj = soapObject.getProperty("OrganizationGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                organizationGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                organizationGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("OrganizationName"))
        {
            Object obj = soapObject.getProperty("OrganizationName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                organizationName = j.toString();
            }else if (obj!= null && obj instanceof String){
                organizationName = (String) obj;
            }
        }
        if (soapObject.hasProperty("Pin"))
        {
            Object obj = soapObject.getProperty("Pin");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pin = j.toString();
            }else if (obj!= null && obj instanceof String){
                pin = (String) obj;
            }
        }
        if (soapObject.hasProperty("RoleGuid"))
        {
            Object obj = soapObject.getProperty("RoleGuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                roleGuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                roleGuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("RoleName"))
        {
            Object obj = soapObject.getProperty("RoleName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                roleName = j.toString();
            }else if (obj!= null && obj instanceof String){
                roleName = (String) obj;
            }
        }
        if (soapObject.hasProperty("UserDetails"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("UserDetails");
            userDetails =  new UserDetailsModel (j);
            
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return null;
            case 1:
                return createdAt;
            case 2:
                return email;
            case 3:
                return guid;
            case 4:
                return isActivated;
            case 5:
                return isAdministrator;
            case 6:
                return isDisabled;
            case 7:
                return organizationGuid;
            case 8:
                return organizationName;
            case 9:
                return pin;
            case 10:
                return roleGuid;
            case 11:
                return roleName;
            case 12:
                return userDetails;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 13;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = null;
                info.name = "ExtensionData";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CreatedAt";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Email";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Guid";
                break;
            case 4:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "IsActivated";
                break;
            case 5:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "IsAdministrator";
                break;
            case 6:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "IsDisabled";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "OrganizationGuid";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "OrganizationName";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Pin";
                break;
            case 10:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "RoleGuid";
                break;
            case 11:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "RoleName";
                break;
            case 12:
                info.type = UserDetailsModel.class;
                info.name = "UserDetails";
                break;
        }
    }

    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
