package IPclLicenseServiceContract;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/29/2017 12:54:15 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class UserDetailsModel implements KvmSerializable {
    

    public String createdAt;
    public String firstName;
    public char gender;
    public String lastName;
    public String lastUpdateDate;
    public String telephoneNumber;
    public String title;
    
    public UserDetailsModel(){}
    
    public UserDetailsModel(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ExtensionData"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ExtensionData");

            
        }
        if (soapObject.hasProperty("CreatedAt"))
        {
            Object obj = soapObject.getProperty("CreatedAt");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                createdAt = j.toString();
            }else if (obj!= null && obj instanceof String){
                createdAt = (String) obj;
            }
        }
        if (soapObject.hasProperty("FirstName"))
        {
            Object obj = soapObject.getProperty("FirstName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                firstName = j.toString();
            }else if (obj!= null && obj instanceof String){
                firstName = (String) obj;
            }
        }
        if (soapObject.hasProperty("Gender"))
        {
            Object obj = soapObject.getProperty("Gender");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                gender = ' ';
            }else if (obj!= null && obj instanceof String){
                gender = ' ';
            }
        }
        if (soapObject.hasProperty("LastName"))
        {
            Object obj = soapObject.getProperty("LastName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lastName = j.toString();
            }else if (obj!= null && obj instanceof String){
                lastName = (String) obj;
            }
        }
        if (soapObject.hasProperty("LastUpdateDate"))
        {
            Object obj = soapObject.getProperty("LastUpdateDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lastUpdateDate = j.toString();
            }else if (obj!= null && obj instanceof String){
                lastUpdateDate = (String) obj;
            }
        }
        if (soapObject.hasProperty("TelephoneNumber"))
        {
            Object obj = soapObject.getProperty("TelephoneNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                telephoneNumber = j.toString();
            }else if (obj!= null && obj instanceof String){
                telephoneNumber = (String) obj;
            }
        }
        if (soapObject.hasProperty("Title"))
        {
            Object obj = soapObject.getProperty("Title");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                title = j.toString();
            }else if (obj!= null && obj instanceof String){
                title = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return null;
            case 1:
                return createdAt;
            case 2:
                return firstName;
            case 3:
                return gender;
            case 4:
                return lastName;
            case 5:
                return lastUpdateDate;
            case 6:
                return telephoneNumber;
            case 7:
                return title;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 8;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = null;
                info.name = "ExtensionData";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CreatedAt";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "FirstName";
                break;
            case 3:
                info.type = null; // Property Type Is Not supported;
                info.name = "Gender";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LastName";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LastUpdateDate";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TelephoneNumber";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Title";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
